// WARNING: This file has been generated by a tool!

import { IPrintOption } from "./types";
            
export const data : IPrintOption[] = [
  {
    "id": "photo-paper-poster",
    "name": "Photo Paper Poster",
    "sizes": [
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 21.94,
        "weight": 500
      },
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 31.79,
        "weight": 500
      },
      {
        "id": "12x10",
        "widthInches": 12,
        "heightInches": 10,
        "priceAUD": 31.79,
        "weight": 500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 46.78,
        "weight": 500
      },
      {
        "id": "15x10",
        "widthInches": 15,
        "heightInches": 10,
        "priceAUD": 46.78,
        "weight": 500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 46.78,
        "weight": 500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 46.78,
        "weight": 500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 72.23,
        "weight": 500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 72.23,
        "weight": 500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 80.28,
        "weight": 500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 72.23,
        "weight": 500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 88.11,
        "weight": 500
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 88.11,
        "weight": 500
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 103.12,
        "weight": 500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 122.99,
        "weight": 500
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 124,
        "weight": 500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 142.92,
        "weight": 1000
      },
      {
        "id": "30x30",
        "widthInches": 30,
        "heightInches": 30,
        "priceAUD": 167.62,
        "weight": 1000
      },
      {
        "id": "30x40",
        "widthInches": 30,
        "heightInches": 40,
        "priceAUD": 189,
        "weight": 1000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 210.1,
        "weight": 1000
      },
      {
        "id": "40x40",
        "widthInches": 40,
        "heightInches": 40,
        "priceAUD": 216.59,
        "weight": 1000
      },
      {
        "id": "60x40",
        "widthInches": 60,
        "heightInches": 40,
        "priceAUD": 271.5,
        "weight": 1000
      }
    ]
  },
  {
    "id": "canvas",
    "name": "Canvas",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 168.75,
        "weight": 1000
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 186.56,
        "weight": 1000
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 186.56,
        "weight": 1000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 186.56,
        "weight": 1000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 198.99,
        "weight": 1000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 218.75,
        "weight": 1000
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 222.11,
        "weight": 1000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 237,
        "weight": 1000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 224.36,
        "weight": 1000
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 237,
        "weight": 1000
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 322.5,
        "weight": 1000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 273,
        "weight": 1000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 322.5,
        "weight": 2000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 381,
        "weight": 2000
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 450,
        "weight": 2000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 549,
        "weight": 2000
      },
      {
        "id": "60x40",
        "widthInches": 60,
        "heightInches": 40,
        "priceAUD": 810,
        "weight": 3000
      }
    ]
  },
  {
    "id": "matboard",
    "name": "Matboard",
    "sizes": [
      {
        "id": "9x6",
        "widthInches": 9,
        "heightInches": 6,
        "priceAUD": 23.79,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 58.98,
        "weight": 1500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 55.87,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 87.64,
        "weight": 1500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 92.63,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 137.3,
        "weight": 1500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 182.03,
        "weight": 1500
      }
    ]
  },
  {
    "id": "alumalux",
    "name": "Alumalux",
    "sizes": [
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 162.59,
        "weight": 1000
      },
      {
        "id": "14x11",
        "widthInches": 14,
        "heightInches": 11,
        "priceAUD": 178.76,
        "weight": 1000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 205.64,
        "weight": 1000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 218.75,
        "weight": 1000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 223.04,
        "weight": 1000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 246,
        "weight": 1000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 255,
        "weight": 1000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 382.5,
        "weight": 1000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 460.5,
        "weight": 1000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 552,
        "weight": 1500
      },
      {
        "id": "30x30",
        "widthInches": 30,
        "heightInches": 30,
        "priceAUD": 574.5,
        "weight": 1500
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 766.5,
        "weight": 1500
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 843,
        "weight": 3000
      },
      {
        "id": "60x38",
        "widthInches": 60,
        "heightInches": 38,
        "priceAUD": 1456.5,
        "weight": 3000
      }
    ]
  },
  {
    "id": "acrylic",
    "name": "Acrylic",
    "sizes": [
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 209.79,
        "weight": 2000
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 220.16,
        "weight": 2000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 222.75,
        "weight": 2000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 220.16,
        "weight": 2000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 228,
        "weight": 2000
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 231,
        "weight": 2000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 277.5,
        "weight": 2000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 286.5,
        "weight": 2000
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 334.5,
        "weight": 2000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 405,
        "weight": 2000
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 390,
        "weight": 2000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 474,
        "weight": 1500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 559.5,
        "weight": 1500
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 753,
        "weight": 1500
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 840,
        "weight": 4000
      },
      {
        "id": "40x40",
        "widthInches": 40,
        "heightInches": 40,
        "priceAUD": 1168.5,
        "weight": 4000
      }
    ]
  },
  {
    "id": "photo-paper-framed",
    "name": "Photo Paper Framed",
    "sizes": [
      {
        "id": "10x8",
        "widthInches": 10,
        "heightInches": 8,
        "priceAUD": 170.24,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 170.24,
        "weight": 1500
      },
      {
        "id": "16x11",
        "widthInches": 16,
        "heightInches": 11,
        "priceAUD": 196.91,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 198.99,
        "weight": 1500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 224.36,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 246,
        "weight": 3000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 270,
        "weight": 3000
      },
      {
        "id": "10x8",
        "widthInches": 10,
        "heightInches": 8,
        "priceAUD": 154.44,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 164.16,
        "weight": 1500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 189,
        "weight": 1500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 203.84,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 214.76,
        "weight": 1500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 218.75,
        "weight": 1500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 224,
        "weight": 1500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 224,
        "weight": 1500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 231,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 231,
        "weight": 1500
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 252,
        "weight": 1500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 297,
        "weight": 4000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 315,
        "weight": 4000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 345,
        "weight": 4000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 414,
        "weight": 10000
      }
    ]
  }
];