// WARNING: This file has been generated by a tool!

import { IPrintOption } from "./types";
            
export const data : IPrintOption[] = [
  {
    "id": "photo-paper-poster",
    "name": "Photo Paper Poster",
    "sizes": [
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 22,
        "weight": 500
      },
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 32,
        "weight": 500
      },
      {
        "id": "12x10",
        "widthInches": 12,
        "heightInches": 10,
        "priceAUD": 32,
        "weight": 500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 47,
        "weight": 500
      },
      {
        "id": "15x10",
        "widthInches": 15,
        "heightInches": 10,
        "priceAUD": 47,
        "weight": 500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 47,
        "weight": 500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 47,
        "weight": 500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 72,
        "weight": 500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 72,
        "weight": 500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 80,
        "weight": 500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 72,
        "weight": 500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 88,
        "weight": 500
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 88,
        "weight": 500
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 110,
        "weight": 500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 130,
        "weight": 500
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 130,
        "weight": 500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 150,
        "weight": 1000
      },
      {
        "id": "30x30",
        "widthInches": 30,
        "heightInches": 30,
        "priceAUD": 170,
        "weight": 1000
      },
      {
        "id": "30x40",
        "widthInches": 30,
        "heightInches": 40,
        "priceAUD": 190,
        "weight": 1000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 210,
        "weight": 1000
      },
      {
        "id": "40x40",
        "widthInches": 40,
        "heightInches": 40,
        "priceAUD": 220,
        "weight": 1000
      },
      {
        "id": "60x40",
        "widthInches": 60,
        "heightInches": 40,
        "priceAUD": 280,
        "weight": 1000
      }
    ]
  },
  {
    "id": "canvas",
    "name": "Canvas",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 170,
        "weight": 1000
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 190,
        "weight": 1000
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 190,
        "weight": 1000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 190,
        "weight": 1000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 200,
        "weight": 1000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 220,
        "weight": 1000
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 230,
        "weight": 1000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 240,
        "weight": 1000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 230,
        "weight": 1000
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 240,
        "weight": 1000
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 330,
        "weight": 1000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 280,
        "weight": 1000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 330,
        "weight": 2000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 390,
        "weight": 2000
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 450,
        "weight": 2000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 550,
        "weight": 2000
      },
      {
        "id": "60x40",
        "widthInches": 60,
        "heightInches": 40,
        "priceAUD": 810,
        "weight": 3000
      }
    ]
  },
  {
    "id": "matboard",
    "name": "Matboard",
    "sizes": [
      {
        "id": "9x6",
        "widthInches": 9,
        "heightInches": 6,
        "priceAUD": 24,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 59,
        "weight": 1500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 56,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 88,
        "weight": 1500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 93,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 140,
        "weight": 1500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 190,
        "weight": 1500
      }
    ]
  },
  {
    "id": "alumalux",
    "name": "Alumalux",
    "sizes": [
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 170,
        "weight": 1000
      },
      {
        "id": "14x11",
        "widthInches": 14,
        "heightInches": 11,
        "priceAUD": 180,
        "weight": 1000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 210,
        "weight": 1000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 220,
        "weight": 1000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 230,
        "weight": 1000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 250,
        "weight": 1000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 260,
        "weight": 1000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 390,
        "weight": 1000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 470,
        "weight": 1000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 560,
        "weight": 1500
      },
      {
        "id": "30x30",
        "widthInches": 30,
        "heightInches": 30,
        "priceAUD": 580,
        "weight": 1500
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 770,
        "weight": 1500
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 850,
        "weight": 3000
      },
      {
        "id": "60x38",
        "widthInches": 60,
        "heightInches": 38,
        "priceAUD": 1460,
        "weight": 3000
      }
    ]
  },
  {
    "id": "acrylic",
    "name": "Acrylic",
    "sizes": [
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 210,
        "weight": 2000
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 220,
        "weight": 2000
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 230,
        "weight": 2000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 220,
        "weight": 2000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 230,
        "weight": 2000
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 240,
        "weight": 2000
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 280,
        "weight": 2000
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 290,
        "weight": 2000
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 340,
        "weight": 2000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 410,
        "weight": 2000
      },
      {
        "id": "24x24",
        "widthInches": 24,
        "heightInches": 24,
        "priceAUD": 390,
        "weight": 2000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 480,
        "weight": 1500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 560,
        "weight": 1500
      },
      {
        "id": "40x30",
        "widthInches": 40,
        "heightInches": 30,
        "priceAUD": 760,
        "weight": 1500
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 840,
        "weight": 4000
      },
      {
        "id": "40x40",
        "widthInches": 40,
        "heightInches": 40,
        "priceAUD": 1170,
        "weight": 4000
      }
    ]
  },
  {
    "id": "photo-paper-framed",
    "name": "Photo Paper Framed",
    "sizes": [
      {
        "id": "10x8",
        "widthInches": 10,
        "heightInches": 8,
        "priceAUD": 170,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 170,
        "weight": 1500
      },
      {
        "id": "16x11",
        "widthInches": 16,
        "heightInches": 11,
        "priceAUD": 200,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 200,
        "weight": 1500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 230,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 250,
        "weight": 3000
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 270,
        "weight": 3000
      },
      {
        "id": "10x8",
        "widthInches": 10,
        "heightInches": 8,
        "priceAUD": 160,
        "weight": 1500
      },
      {
        "id": "12x8",
        "widthInches": 12,
        "heightInches": 8,
        "priceAUD": 170,
        "weight": 1500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 190,
        "weight": 1500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 210,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 220,
        "weight": 1500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 220,
        "weight": 1500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 230,
        "weight": 1500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 230,
        "weight": 1500
      },
      {
        "id": "20x20",
        "widthInches": 20,
        "heightInches": 20,
        "priceAUD": 240,
        "weight": 1500
      },
      {
        "id": "24x16",
        "widthInches": 24,
        "heightInches": 16,
        "priceAUD": 240,
        "weight": 1500
      },
      {
        "id": "24x20",
        "widthInches": 24,
        "heightInches": 20,
        "priceAUD": 260,
        "weight": 1500
      },
      {
        "id": "30x20",
        "widthInches": 30,
        "heightInches": 20,
        "priceAUD": 300,
        "weight": 4000
      },
      {
        "id": "30x24",
        "widthInches": 30,
        "heightInches": 24,
        "priceAUD": 320,
        "weight": 4000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 350,
        "weight": 4000
      },
      {
        "id": "45x30",
        "widthInches": 45,
        "heightInches": 30,
        "priceAUD": 420,
        "weight": 10000
      }
    ]
  }
];