// WARNING: This file has been generated by a tool!

import { IPrintOption } from "./types";
            
export const data : IPrintOption[] = [
  {
    "id": "photo-paper-poster",
    "name": "Photo Paper Poster",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 39,
        "weight": 12.8,
        "meta": {
          "printfulVariantId": "6872"
        }
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 42,
        "weight": 18.4,
        "meta": {
          "printfulVariantId": "6873"
        }
      },
      {
        "id": "14x14",
        "widthInches": 14,
        "heightInches": 14,
        "priceAUD": 46,
        "weight": 24.9,
        "meta": {
          "printfulVariantId": "6874"
        }
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 49,
        "weight": 25.5,
        "meta": {
          "printfulVariantId": "6875"
        }
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 50,
        "weight": 28.3,
        "meta": {
          "printfulVariantId": "6876"
        }
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 51,
        "weight": 32.6,
        "meta": {
          "printfulVariantId": "6877"
        }
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 53,
        "weight": 41.1,
        "meta": {
          "printfulVariantId": "6878"
        }
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 56,
        "weight": 42.5,
        "meta": {
          "printfulVariantId": "6879"
        }
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 60,
        "weight": 56.7,
        "meta": {
          "printfulVariantId": "6880"
        }
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 80,
        "weight": 107.7,
        "meta": {
          "printfulVariantId": "7845"
        }
      }
    ]
  },
  {
    "id": "canvas",
    "name": "Canvas",
    "sizes": [
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 140,
        "weight": 1236,
        "meta": {
          "printfulVariantId": "6"
        }
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 160,
        "weight": 1718,
        "meta": {
          "printfulVariantId": "7"
        }
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 120,
        "weight": 739.9,
        "meta": {
          "printfulVariantId": "823"
        }
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 130,
        "weight": 1451.5,
        "meta": {
          "printfulVariantId": "824"
        }
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 200,
        "weight": 2795.3,
        "meta": {
          "printfulVariantId": "825"
        }
      }
    ]
  },
  {
    "id": "photo-paper-framed",
    "name": "Photo Paper Framed",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 89,
        "weight": 453.6,
        "meta": {
          "printfulVariantId": "6883"
        }
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 110,
        "weight": 567,
        "meta": {
          "printfulVariantId": "6884"
        }
      },
      {
        "id": "14x14",
        "widthInches": 14,
        "heightInches": 14,
        "priceAUD": 120,
        "weight": 708.7,
        "meta": {
          "printfulVariantId": "6885"
        }
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 120,
        "weight": 595.3,
        "meta": {
          "printfulVariantId": "6886"
        }
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 130,
        "weight": 623.7,
        "meta": {
          "printfulVariantId": "6887"
        }
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 130,
        "weight": 850.5,
        "meta": {
          "printfulVariantId": "6888"
        }
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 160,
        "weight": 765.4,
        "meta": {
          "printfulVariantId": "6889"
        }
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 150,
        "weight": 1048.9,
        "meta": {
          "printfulVariantId": "6890"
        }
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 170,
        "weight": 1445.8,
        "meta": {
          "printfulVariantId": "6891"
        }
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 220,
        "weight": 2466.4,
        "meta": {
          "printfulVariantId": "7846"
        }
      }
    ]
  }
];