// WARNING: This file has been generated by a tool!

import { IPrintOption } from "./types";
            
export const data : IPrintOption[] = [
  {
    "id": "photo-paper-poster",
    "name": "Photo Paper Poster",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 37,
        "weight": 500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 41,
        "weight": 500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 44,
        "weight": 500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 48,
        "weight": 500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 49,
        "weight": 500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 51,
        "weight": 500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 55,
        "weight": 500
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 58,
        "weight": 500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 78,
        "weight": 1000
      }
    ]
  },
  {
    "id": "canvas",
    "name": "Canvas",
    "sizes": [
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 120,
        "weight": 1000
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 130,
        "weight": 1000
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 130,
        "weight": 1000
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 160,
        "weight": 1000
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 190,
        "weight": 2000
      }
    ]
  },
  {
    "id": "photo-paper-framed",
    "name": "Photo Paper Framed",
    "sizes": [
      {
        "id": "10x10",
        "widthInches": 10,
        "heightInches": 10,
        "priceAUD": 87,
        "weight": 1500
      },
      {
        "id": "12x12",
        "widthInches": 12,
        "heightInches": 12,
        "priceAUD": 99,
        "weight": 1500
      },
      {
        "id": "16x12",
        "widthInches": 16,
        "heightInches": 12,
        "priceAUD": 120,
        "weight": 1500
      },
      {
        "id": "18x12",
        "widthInches": 18,
        "heightInches": 12,
        "priceAUD": 120,
        "weight": 1500
      },
      {
        "id": "16x16",
        "widthInches": 16,
        "heightInches": 16,
        "priceAUD": 130,
        "weight": 1500
      },
      {
        "id": "20x16",
        "widthInches": 20,
        "heightInches": 16,
        "priceAUD": 150,
        "weight": 1500
      },
      {
        "id": "18x18",
        "widthInches": 18,
        "heightInches": 18,
        "priceAUD": 150,
        "weight": 1500
      },
      {
        "id": "24x18",
        "widthInches": 24,
        "heightInches": 18,
        "priceAUD": 170,
        "weight": 1500
      },
      {
        "id": "36x24",
        "widthInches": 36,
        "heightInches": 24,
        "priceAUD": 220,
        "weight": 1500
      }
    ]
  }
];