export = {
    "eventName": "shippingrates.fetch",
    "mode": "Live",
    "createdOn": "2018-04-07T08:14:25.9555521Z",
    "content": {
        "token": "e8c340d6-4d7b-4b75-ae2d-bc0e283df8bc",
        "isRecurringOrder": false,
        "parentToken": null,
        "parentInvoiceNumber": null,
        "subscriptionId": null,
        "currency": "aud",
        "creationDate": "2018-04-06T03:02:50Z",
        "modificationDate": "2018-04-07T08:14:22Z",
        "recoveredFromCampaignId": null,
        "status": "InProgress",
        "paymentStatus": null,
        "email": "mike.cann@gmail.com",
        "willBePaidLater": false,
        "billingAddressFirstName": null,
        "billingAddressName": "Mike",
        "billingAddressCompanyName": "",
        "billingAddressAddress1": "3 / 25 Hardy Street",
        "billingAddressAddress2": "",
        "billingAddressCity": "South Perth",
        "billingAddressCountry": "AU",
        "billingAddressProvince": "",
        "billingAddressPostalCode": "6151",
        "billingAddressPhone": "",
        "billingAddress": {
            "fullName": "Mike",
            "firstName": null,
            "name": "Mike",
            "company": "",
            "address1": "3 / 25 Hardy Street",
            "address2": "",
            "fullAddress": "3 / 25 Hardy Street",
            "city": "South Perth",
            "country": "AU",
            "postalCode": "6151",
            "province": "",
            "phone": "",
            "vatNumber": null
        },
        "shippingAddressFirstName": null,
        "shippingAddressName": "Mike",
        "shippingAddressCompanyName": "",
        "shippingAddressAddress1": "3 / 25 Hardy Street",
        "shippingAddressAddress2": "",
        "shippingAddressCity": "South Perth",
        "shippingAddressCountry": "AU",
        "shippingAddressProvince": "",
        "shippingAddressPostalCode": "6151",
        "shippingAddressPhone": "",
        "shippingAddress": {
            "fullName": "Mike",
            "firstName": null,
            "name": "Mike",
            "company": "",
            "address1": "3 / 25 Hardy Street",
            "address2": "",
            "fullAddress": "3 / 25 Hardy Street",
            "city": "South Perth",
            "country": "AU",
            "postalCode": "6151",
            "province": "",
            "phone": "",
            "vatNumber": null
        },
        "shippingAddressSameAsBilling": false,
        "creditCardLast4Digits": null,
        "trackingNumber": null,
        "trackingUrl": null,
        "shippingFees": null,
        "shippingProvider": null,
        "shippingMethod": null,
        "cardHolderName": null,
        "paymentMethod": 0,
        "notes": null,
        "customFieldsJson": "[]",
        "userId": "064c296c-5e74-40dd-9338-e40b763e96de",
        "completionDate": null,
        "paymentGatewayUsed": "None",
        "taxProvider": "Default",
        "discounts": [],
        "plans": [],
        "taxes": [],
        "user": null,
        "items": [
            {
                "paymentSchedule": {
                    "interval": 0,
                    "intervalCount": 1,
                    "trialPeriodInDays": null,
                    "startsOn": "2018-04-07T00:00:00Z"
                },
                "token": "e8c340d6-4d7b-4b75-ae2d-bc0e283df8bc",
                "name": "Watermans Observatory",
                "price": 220,
                "quantity": 1,
                "fileGuid": null,
                "url": "https://aboveunder.com/products/au0162-watermans-observatory.json",
                "id": "au0162-watermans-observatory-photo-paper-framed-36x24-printful",
                "initialData": "",
                "description": `'Watermans Observatory' printed on 'Photo Paper Framed' at size '36" x 24"' using '🌎 Global Printer'`,
                "categories": [],
                "weight": 2466.4,
                "image": "/images/products/thumb/Watermans-Observatory.jpg",
                "originalPrice": null,
                "uniqueId": "bf1b879b-7e07-4e43-882c-f5d8d92e1619",
                "stackable": true,
                "minQuantity": null,
                "maxQuantity": null,
                "addedOn": "2018-04-07T08:14:17Z",
                "modificationDate": "2018-04-07T08:14:17Z",
                "shippable": true,
                "taxable": true,
                "duplicatable": false,
                "width": null,
                "height": null,
                "length": null,
                "metadata": null,
                "totalPrice": 220,
                "totalWeight": 2466.4,
                "taxes": [],
                "alternatePrices": {},
                "customFields": [
                    {
                        "name": "Note to Above Under",
                        "displayValue": "",
                        "operation": null,
                        "type": "textarea",
                        "options": "",
                        "required": false,
                        "value": "",
                        "optionsArray": null
                    }
                ],
                "unitPrice": 220,
                "hasDimensions": false
            }
        ],
        "refunds": [],
        "lang": "en",
        "refundsAmount": 0,
        "adjustedAmount": 220,
        "finalGrandTotal": 220,
        "totalNumberOfItems": 0,
        "invoiceNumber": "e8c340d6-4d7b-4b75-ae2d-bc0e283df8bc",
        "billingAddressComplete": true,
        "shippingAddressComplete": true,
        "shippingMethodComplete": false,
        "rebateAmount": 0,
        "subtotal": 220,
        "baseTotal": 220,
        "itemsTotal": 220,
        "taxableTotal": 220,
        "grandTotal": 220,
        "total": 220,
        "totalWeight": 2466.4,
        "totalRebateRate": 0,
        "customFields": [],
        "shippingEnabled": true,
        "numberOfItemsInOrder": 1,
        "paymentTransactionId": "",
        "metadata": {},
        "taxesTotal": 0,
        "itemsCount": 1,
        "summary": {
            "subtotal": 220,
            "taxableTotal": 220,
            "total": 220,
            "payableNow": 220,
            "paymentMethod": 0,
            "taxes": [],
            "adjustedTotal": 220,
            "shipping": null
        },
        "ipAddress": "61.245.143.206",
        "hasSubscriptions": false
    }
};