"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const csvtojson = require("csvtojson");
const fs = require("fs");
const prodMapping = {
    "Metallic": { id: "photo-paper-poster", name: "Photo Paper Poster" },
    "Canvas": { id: "canvas", name: "Canvas" },
    "Acrylic": { id: "acrylic", name: "Acrylic" },
    "Matboard": { id: "matboard", name: "Matboard" },
    "Alumalux": { id: "alumalux", name: "Alumalux" },
    "Standard Frame": { id: "photo-paper-framed", name: "Photo Paper Framed" },
    "Frame": { id: "photo-paper-framed", name: "Photo Paper Framed" },
};
async function run() {
    const csvPath = `${__dirname}/../data/Above Under Pricing - Fitz Pricing.csv`;
    const tsPath = `${__dirname}/../src/lib/defaultPrintOptions.ts`;
    var options = {};
    console.log(`Importing CSV from: ${csvPath}`);
    csvtojson()
        .fromFile(csvPath)
        .on('json', (json) => {
        if (!json.Product)
            return;
        var mapping = prodMapping[json.Product];
        if (mapping == null)
            throw Error("No mapping found for: " + json.Product);
        if (!options.hasOwnProperty(mapping.id)) {
            options[mapping.id] = {
                id: prodMapping[json.Product].id,
                name: prodMapping[json.Product].name,
                sizes: []
            };
        }
        else {
            options[mapping.id].sizes.push({
                id: `${json.Width}x${json.Height}`,
                widthInches: parseInt(json.Width),
                heightInches: parseInt(json.Height),
                priceAUD: parseFloat(json["My Price"]),
                weight: parseFloat(json.Weight) * 1000,
            });
        }
    })
        .on('done', async (error) => {
        if (error)
            throw new Error(error);
        var outp = [];
        for (var key in options)
            outp.push(options[key]);
        fs.writeFileSync(tsPath, `// WARNING: This file has been generated by a tool!

import { IPrintOption } from "./types";
            
export const data : IPrintOption[] = ${JSON.stringify(outp, null, 2)};`);
    });
}
run();
